package route

import (
	_ "library-api/docs" // docs is generated by Swag CLI, you have to import it.
	"os"

	echoSwagger "github.com/swaggo/echo-swagger" // echo-swagger middleware

	"library-api/config"     // Import the config package
	"library-api/handler"    // Import the handler package
	"library-api/mw"         // Import the repository package
	"library-api/repository" // Import the repository package

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
)

func ExecRouter() {
	e := echo.New()

	// Initialize the repository
	userRepo := repository.NewUserRepository(config.DB)
	transRepo := repository.NewTransactionRepository(config.DB)
	bookRepo := repository.NewBookRepository(config.DB)
	rentRepo := repository.NewRentRepository(config.DB)

	// Initialize the handlers
	userHandler := handler.NewUserHandler(userRepo)
	transHandler := handler.NewTransactionHandler(transRepo)
	bookHandler := handler.NewBookHandler(bookRepo)
	rentHandler := handler.NewRentHandler(rentRepo)

	// Middleware
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())

	// Routes
	g := e.Group("/api/v1")

	//
	g.GET("/swagger/*", echoSwagger.WrapHandler) // Swagger documentation route

	g.POST("/users/register", userHandler.CreateUser)                   // Create a new user
	g.POST("/users/login", userHandler.LoginUser)                       // login
	g.GET("/users/me", userHandler.GetUserByID, mw.CheckAuthMiddleware) // Get current user
	g.PUT("/users/me", userHandler.UpdateUser, mw.CheckAuthMiddleware)  // Update current user
	g.GET("/users/refresh-token", userHandler.RefreshToken)             // Get user by ID

	// Books routes
	g.GET("/books", bookHandler.GetAllBooks)      // Get all books
	g.GET("/books/:id", bookHandler.GetBooksByID) // Get book by ID

	// Rent routes
	g.GET("/rents", rentHandler.GetAllRent, mw.CheckAuthMiddleware)            // Get all rents for a user
	g.GET("/rents/:id", rentHandler.GetRentByID, mw.CheckAuthMiddleware)       // Get rent by ID for a user
	g.POST("/rents", rentHandler.CreateRent, mw.CheckAuthMiddleware)           // Create a new rent for a user
	g.PUT("/rents/return/:id", rentHandler.ReturnRent, mw.CheckAuthMiddleware) // Return a rent for a user

	// Transaction routes
	g.POST("/transactions/create-transaction", transHandler.CreateTransaction, mw.CheckAuthMiddleware)    // Create a new transaction, can be topup or rent
	g.PUT("/transactions/update-transaction/:id", transHandler.UpdateTransaction, mw.CheckAuthMiddleware) // Update transaction by ID, confirm to complete the transaction
	g.GET("/transactions", transHandler.GetAllTransaction, mw.CheckAuthMiddleware)                        // Get all transactions for a user
	g.GET("/transactions/:id", transHandler.GetTransactionByID, mw.CheckAuthMiddleware)                   // Get transaction by ID for a user

	// Start server
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080" // Default port if not set in environment variables
	}
	e.Logger.Fatal(e.Start(":" + port))
}
